version: '2'

services:
  nginx:
    image: nginx
    container_name: laravel-project-nginx
    ports:
      - 80:80
    volumes:
      - ./src:/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./docker/php
    container_name: laravel-project-php
    volumes:
      - ./src:/src
  mysql:
    build: ./docker/mysql
    container_name: laravel-project-mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel-project-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
